#!/data/data/com.termux/files/usr/bin/sh
LOG="/data/data/com.termux/files/opt/lissi/fc/LISSI.log"
adb connect localhost
while true
do
    DEVICES=`adb devices|wc -l`
    if [ 2 -eq "$DEVICES" ] ; then
	echo "`date` WAR no device connected" >>$LOG
    fi

    if [ "$DEVICES" -gt 2 ] ; then
	echo "`date` INF found adb device(s): `adb devices`" >>$LOG
	break
    fi
    sleep 60
    adb connect localhost
done
exit
