#!/bin/bash

CONF="/tmp/autoadb.conf"
RUN="/tmp/autoadb2zenity"

# BASEDIR="/opt/autoadb"
BASEDIR=`dirname $0`
if [ " $BASEDIR" == " ." ];then
    BASEDIR=`pwd`
fi

LOG=/$BASEDIR/log/autoadb_`date +"%b-%d-%y"`.log
#mkdir $BASEDIR/log 2>/dev/null

#echo "DISPLAY=$DISPLAY" > $CONF
#echo "USER=$USER" >> $CONF
#chmod 666 $CONF 2>/dev/null

source $CONF
source ${BASEDIR}/mesglib

#echo "DISPLAY=$DISPLAY" > $CONF
#echo "USER=$USER" >> $CONF
#chmod 666 $CONF 2>/dev/null

echo "DISPLAY=$DISPLAY"
echo "USER=$USER"


#err2x "\"Hi du ekelhafter MOTHERFUCKER _PISS OFF!!\""
#info2x "\"SACH ICH DOCH MOTHERFUCKER _PISS 2x OFF!!\""

#logfile o.ä
tmpfn="/tmp/hotplug_l10l.log"
hotpluglog="/tmp/hotplug.log"
tail -n 18 $hotpluglog > $tmpfn
text2x $tmpfn

